### ISSUE TITLE
after connect with sollet, cant deposite sol into the protocal.

### ISSUE THREAD

**Issue by Shenwansanat** [jet-lab/jet-v1#58]
I have changed the wallet network to kovan. Even though it is not possible to deposit my sol, the button is spinning all the time.

**Comment by GHesericsu** [comment]
This should be fixed.

**Comment by Shenwansanat** [comment]
unfortunately it is not fixed, after your reply, I have tried many times, it turns out the same like before.

**Comment by Shenwansanat** [comment]
the issue is fixed，thank you team jet!

**Comment by GHesericsu** [comment]
:)
